---
title: "PEARL Weekly Situation Report"
author: "National Tuberculosis Program, Kiribati"
date: "`r Sys.Date()`"
format:
  pdf:
    toc: true
    number-sections: true
    output-file: "weekly_sitrep.pdf"
execute:
  echo: true
  message: false
  warning: false
---

# Load Data

```{r}
#| label: Load data

# Load necessary libraries
library(here)

# Source scripts for data loading and tidying
source(here("R", "02_load_data.R"))
source(here("R", "03_tidy_data.R"))

# Automatically source all scripts in /data-raw/R that start with 05 or 06
script_files <- list.files(path = here("R"), pattern = "^(05|06).*\\.R$", full.names = TRUE)
lapply(script_files, source)
```

# Activity This Week

## Summary Table

```{r}
#| label: Summary flextable
print(table_06.01)
```

# Screening Progress

```{r}
#| label: Progress plots
print(map_05.07)
```

```{r}
#| label: Age pyramid
print(plot_05.02)
```

```{r}
#| label: EA props
print(plot_05.03)
```

## Weekly activities over time

```{r}
#| label: Weekly activities
print(plot_05.01)
```

```{r}
#| label: Weekly quality
print(plot_05.08)
```

## Cumulative screening participation and coverage by village

```{r}
#| label: Cumulative village

print(plot_05.05)
```

## Coverage progress by village

```{r}
#| label: Cumulative village prop

print(plot_05.04)
```

# TB Preventive Treatment

*TBD*

# Linkage to Care

*TBD*

# Plan for Next Week

*TBD*

```{r}
#| label: Move report to the right place

# Ensure reports directory exists
dir.create(here("reports"), showWarnings = FALSE)

# Define new filename with date
new_filename <- here("reports", paste0("weekly_sitrep_", Sys.Date(), ".pdf"))

# Move the file after rendering
file.rename("weekly_sitrep.pdf", new_filename)

message("Report saved to: ", new_filename)

```
